# test projectje

link:
  webhook-url: 'https://discordapp.com/api/webhooks/600819271672528896/4Q00C-OBrOcr3NtZnI0Uhv_esMGh4vxGXr3yEF30fHgnhM5vYmCsULneessLDy4Ni4-E'
  avatar-url: 'https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/042013/coolblue-logo-web.png?itok=UIFVFjCf'
  username: 'Colablikje12'